stages:
  - build

minimum:
  stage: build
  script:
    - curl -OLs ${TESTING_BASE_URL}/${TESTING_QUARTER}/CIFileExistenceCheck.py
    - curl -OLs ${TESTING_BASE_URL}/${TESTING_QUARTER}/massPullOptions.cfg
    - python3 CIFileExistenceCheck.py massPullOptions.cfg
  artifacts:
    expire_in: 1 week

